# Generated by Django 6.0.4 on 2026-06-01 20:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Traslado', 'Traslado')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MOVIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'STOCK_SUCURSAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_suc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('es_central', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SUCURSAL',
                'managed': False,
            },
        ),
    ]
