# Generated by Django 6.0.4 on 2026-10-10 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora exacta en que ocurrió el evento.')),
                ('usuario_email', models.CharField(db_index=True, help_text='Correo electrónico involucrado en el evento (preservado aun si el usuario se elimina o no existe).', max_length=254)),
                ('evento', models.CharField(choices=[('BAJA_CUENTA', 'Baja voluntaria de cuenta'), ('BAJA_USUARIO', 'Baja administrativa de usuario'), ('ALTA_USUARIO', 'Alta de nuevo usuario'), ('LOGIN_EXITOSO', 'Inicio de sesión exitoso'), ('LOGIN_FALLIDO', 'Intento de inicio de sesión fallido'), ('BLOQUEO_FUERZA_BRUTA', 'Bloqueo por exceso de intentos'), ('CAMBIO_ROL', 'Cambio de rol de usuario'), ('CAMBIO_PASSWORD', 'Cambio o reseteo de contraseña'), ('MOVIMIENTO_STOCK', 'Movimiento de stock registrado')], db_index=True, help_text='Tipo de evento de seguridad auditado.', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle descriptivo o contexto del evento.')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Dirección IP de origen de la solicitud HTTP.', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado al evento si existe en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'usuarios_log_auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
